### ISSUE TITLE
Not showing up as processor

### ISSUE THREAD

**Issue by BrainMonkey** [whiver/nifi-protobuf-processor#1]
Wasn't sure of best way to contact you.  I build the nar and move to the lib directory of nifi. Using . 1.4.0 but it does not show up. 

![](https://i.imgur.com/nvk9FFi.jpg)

**Comment by whiver** [comment]
Hello,
Yes I know in fact the plugin is still under heavy development and is still not really mature.
I don't know when you tried to build the plugin, though now it should build and work on master. I should release a first preview in the next days btw.
Tell me if it still does not work.

**Comment by whiver** [comment]
I just tried to install the plugin in a fresh NiFi and it seems to work:

![image](https://user-images.githubusercontent.com/394565/33721943-28983330-db71-11e7-9515-23a417f86bf2.png)

**Comment by BrainMonkey** [comment]
Tried with current build.  It says its unpacking correctly but still not showing up in processor list. 
![](https://i.imgur.com/9Cv2vSw.jpeg)

**Comment by whiver** [comment]
I think you the problem comes from your nar. With a fresh copy of the master branch, open a terminal and just run `mvn nifi-nar:nar`, then you should have a file named `nifi-protobuf-processor-0.1.0-SNAPSHOT.nar` in your target directory.

Let's try with this file.

**Comment by whiver** [comment]
Just to be sure, I give you my working version of the compiled nar, tell me if it works for you.

[nifi-protobuf-processor-0.1.0-SNAPSHOT.zip](https://github.com/whiver/nifi-protobuf-processor/files/1539787/nifi-protobuf-processor-0.1.0-SNAPSHOT.zip)

**Comment by BrainMonkey** [comment]
I repulled and rebuilt same, same error I tried on two different instances. The .nar you attached worked fine though

**Comment by whiver** [comment]
Glad to hear it works now. Did you build using the `mvn nifi-nar:nar` command?

**Comment by BrainMonkey** [comment]
Yes I did, directly from the project and it built a new nar named the same as the one you attached

**Comment by whiver** [comment]
Did you get any error when you built the nar?

**Comment by BrainMonkey** [comment]
Was all successful . One thing looking at the nifi-app.logs. 

Your had this additional line

 ```fr.whiver.nifi:nifi-protobuf-processor:0.1.0-SNAPSHOT || ./work/nar/extensions/nifi-protobuf-processor-0.1.0-SNAPSHOT.nar-unpacked``` 

after unpacking. Mine did not.

**Comment by whiver** [comment]
Okay my mistake, I just tried to clone the repo and rebuild the project and of course, before packaging the processors into a `.nar` file, you have to build it! So it's quite logical that yours does not work since there is nothing but third-party libraries inside.

To build and package everything you should type:

```
mvn compile
mvn nifi-nar:nar
```

or simply `mvn package`, though it will also build the Docker image.
Sorry for the mistake!
