### ISSUE TITLE
Unable to find the message in protobuf.messageType, Unable to decode data .

### ISSUE THREAD

**Issue by ghost** [whiver/nifi-protobuf-processor#9]
I am trying out a simple flow in Nifi which converts a JSON data into Protobuf type.

Here is the flow which I tried:
```
Generate flow file(contains json message) --> Protobuf Encoder --> Putfile
```
These are the configurations of ProtobufEncoder:
![image](https://user-images.githubusercontent.com/50312320/120328044-0ec6db00-c308-11eb-976b-33b4a11b147b.png)

As shown in the above picture, I am passing a compiled schema file in the schema path property and I set the compile schema property to false.
But the flow files are routing to error queue saying, 
```
Unable to find the message in protobuf.messageType, Unable to decode data.
```

Please suggest me the changes need to be done at configurations. Appreciate your help!!

**Comment by dracomithril** [comment]
I was able to find solution for that
you need to place UpdateAttribute processor before ProtobufDecoder and add there attribute `protobuf.messageType` that correlates with your schema. Now the thing that is happening to me is that JSON contains only one property `id` with long string :(

But I hope that this will help you

**Comment by ghost** [comment]
> I was able to find solution for that
> you need to place UpdateAttribute processor before ProtobufDecoder and add there attribute `protobuf.messageType` that correlates with your schema. Now the thing that is happening to me is that JSON contains only one property `id` with long string :(
> 
> But I hope that this will help you

Thank you! it worked ..
